### ISSUE TITLE
Attempt to call field 'get_hotbar_bg' (a nil value)

### ISSUE THREAD

**Issue by amadin** [D00Med/witchcraft#1]
> 2016-09-18 17:03:26: ERROR[Main]: ModError: Failed to load and run script from /home/ra/minetest-stable-0.4/bin/../mods/witchcraft/init.lua:
> 2016-09-18 17:03:26: ERROR[Main]: ...e/ra/minetest-stable-0.4/bin/../mods/witchcraft/init.lua:49: attempt to call field 'get_hotbar_bg' (a nil value)
> 2016-09-18 17:03:26: ERROR[Main]: stack traceback:
> 2016-09-18 17:03:26: ERROR[Main]:     ...e/ra/minetest-stable-0.4/bin/../mods/witchcraft/init.lua:49: in main chunk

If i comment --default.get_hotbar_bg(0,2.85) at 49 string then:

> ERROR[Main]: ModError: Failed to load and run script from /home/ra/minetest-stable-0.4/bin/../mods/witchcraft/init.lua:
> 2016-09-18 17:17:35: ERROR[Main]: ...e/ra/minetest-stable-0.4/bin/../mods/witchcraft/init.lua:111: attempt to concatenate a nil value
> 2016-09-18 17:17:35: ERROR[Main]: stack traceback:
> 2016-09-18 17:17:35: ERROR[Main]:     ...e/ra/minetest-stable-0.4/bin/../mods/witchcraft/init.lua:111: in main chunk
> 2016-09-18 17:17:35: ERROR[Main]: Check debug.txt for details.

Minetest 0.4.14 stable.

**Comment by D00Med** [comment]
This is strange, the code is almost an exact copy of the shelf from vessels, so if the main game works then this should too. Have you tried using only witchcraft and it's dependencies to try and repeat the error?

**Comment by amadin** [comment]
Only witchcraft and it's dependencies work without errors.

**Comment by D00Med** [comment]
So there is another mod that conflicts with it, what mods were you running?

**Comment by cyian-1756** [comment]
I've run into this issue as well (with other mods) any idea what's causing it?

Edit; Truns out I had a `default = {}` in one of the mods I wrote which was causing the crash

**Comment by D00Med** [comment]
Glad you found the problem
