### ISSUE TITLE
Black texture for Shady Potion

### ISSUE THREAD

**Issue by amadin** [D00Med/witchcraft#3]
If place a shady potion on the floor then it will have a black color.

![screenshot_20161009_135003](https://cloud.githubusercontent.com/assets/13412191/19219877/dc646d0e-8e27-11e6-9897-5e29362b1ace.png)

**Comment by amadin** [comment]
Fixed here https://github.com/amadin/witchcraft/commit/ec8e35bbce2d98c90dd4d5c22fb62e4131b1bc11

**Comment by D00Med** [comment]
Fixed
