### ISSUE TITLE
Crash. attempt to call field 'boom' (a nil value)

### ISSUE THREAD

**Issue by amadin** [D00Med/witchcraft#4]
If try to use "Dodgy Potion" then get crash:

> 2016-10-11 16:59:00: ERROR[Main]: ServerError: Lua: Runtime error from mod 'witchcraft' in callback item_OnUse(): ...п╦я▐ minetest-stable-0.4/bin/../mods/witchcraft/init.lua:2094: attempt to call field 'boom' (a nil value)
> 2016-10-11 16:59:00: ERROR[Main]: stack traceback:
> 2016-10-11 16:59:00: ERROR[Main]:   ...п╦я▐ minetest-stable-0.4/bin/../mods/witchcraft/init.lua:2094: in function <...п╦я▐ minetest-stable-0.4/bin/../mods/witchcraft/init.lua:2092>

Minetest 0.4.14 stable, tnt and fire are installed and activated.

**Comment by D00Med** [comment]
Try it now, I attempted to fix it. 
Thanks for all your help

**Comment by amadin** [comment]
It still crash, do you can reproduce this or this is crash happen only for me?

**Comment by D00Med** [comment]
I can't reproduce it, but I'm not using the latest version(I use a windows dev version). 
It seems to have something to do with the tnt mod
