### ISSUE TITLE
Support newer hunger mods.

### ISSUE THREAD

**Issue by orbea** [D00Med/witchcraft#6]
Is it possible witchcraft could support other hunger mods? I have found hbhunger works well (http://repo.or.cz/minetest_hbhunger.git). This mod additionally relies on hudbars (http://repo.or.cz/minetest_hudbars.git).

**Comment by D00Med** [comment]
Yes, I will add support :)

**Comment by D00Med** [comment]
*if I can

**Comment by orbea** [comment]
Awesome, thanks for the quick reply!

**Comment by orbea** [comment]
@D00Med I switched to `hunger_ng` here. (https://gitlab.com/4w/hunger_ng)

https://notabug.org/orbea/witchcraft/commit/3d6fe81097bf4b07acdd7584abf92513b9bf1b61

Given this repo hasn't been updated since 2017 I am not sure if you are still interested in maintaining this mod, please let me know if you are.

**Comment by D00Med** [comment]
I'm sorry, I had long forgotten about this. I do not maintain my mods anymore, but I do still merge PR's.
